### ISSUE TITLE
Issue with long files piscine D10 ex01 ft_cat.c

### ISSUE THREAD

**Issue by lumaro77** [achrafelkhnissi/1337#1]
The code does not allow to "cat" long files. Maybe a loop until nothing is read from the file could help. Thanks.

**Comment by achrafelkhnissi** [comment]
Hello Mr. Martínez

Among the instruction they gave us in the exercise ex01 in D10 they said:
> You can only do this exercise by declaring a fixed-sized array. This array will have a size limited to a little less than 30ko.

Therefore I intentionally declared a fixed sized buffer in [ft_cat.c](https://github.com/achrafelkhnissi/1337/blob/master/Piscine-2021/DAYS/C10/ex01/srcs/ft_cat.c) line 19:
```c
void	ft_cat(char *file_name)
{
	int		fd;
	char	buf[29000];
	int		ret;

	errno = 0;
	fd = open(file_name, O_RDWR);
```
Note that I forgot to mention that I didn't push this day! I skipped it.
Thank you so much for your issue report!

**Comment by lumaro77** [comment]
Hi,
Thank you for your answer. I was just reviewing my own D10 exercices and found your code. I took the decision of declare (as you) a fixed size buffer (with a constant define in .h) and make a loop reading and writting "buffer size" amount of info until the file is fully read. Thank you for sharing your code.
Regards,

**Comment by achrafelkhnissi** [comment]
You are right! Seems like I misunderstood the exercise. I'lll make sure to correct it! thank you for pointing it out. Really appreciate it.
